# AUTO-GENERATED by scripts/gen_stubs.py — do not edit manually.
# Re-run after `maturin develop` whenever Rust functions are added or changed.
# Rust source: rust/src/lib.rs

def divide_rust(a: float, b: float) -> float:
    """Rust source: rust/src/lib.rs → pub fn divide_rust. Divide *a* by *b*."""
    ...
def multiply_rust(a: float, b: float) -> float:
    """Rust source: rust/src/lib.rs → pub fn multiply_rust. Multiply two numbers."""
    ...
