"""Re-export every public function from the compiled Rust extension.

Any ``#[pyfunction]`` registered in ``rust/src/lib.rs`` is automatically
available here after running ``maturin develop``.  No manual listing needed.

Go To Definition (VS Code / Pylance) follows this wildcard import into
``python/mixedlib/_rust.pyi``, which is auto-generated by
``scripts/gen_stubs.py``.
"""

from mixedlib._rust import *  # noqa: F401, F403
