#!/usr/bin/env python3
"""Auto-generate python/mixedlib/_rust.pyi from the compiled extension.

Run this after every `maturin develop` that adds or changes Rust functions:

    maturin develop
    python scripts/gen_stubs.py

The script combines two sources of information:
  - The live ``mixedlib._rust`` module: which public names exist
  - ``rust/src/lib.rs``: Rust type annotations → Python type annotations

This gives fully-typed stubs without any manual editing.  Pylance's Go To
Definition then navigates from any Python consumer straight to the generated
stub, where every function is listed with its correct signature.
"""

import importlib
import inspect
import json
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).parent.parent
STUB_PATH = REPO_ROOT / "python" / "mixedlib" / "_rust.pyi"
LOCATIONS_PATH = REPO_ROOT / ".maturing" / "_rust_locations.json"
RUST_SOURCE = REPO_ROOT / "rust" / "src" / "lib.rs"

# Map Rust primitive types to Python types.
_RUST_TO_PYTHON: dict[str, str] = {
    "f32": "float",
    "f64": "float",
    "i8": "int",
    "i16": "int",
    "i32": "int",
    "i64": "int",
    "i128": "int",
    "u8": "int",
    "u16": "int",
    "u32": "int",
    "u64": "int",
    "u128": "int",
    "isize": "int",
    "usize": "int",
    "bool": "bool",
    "String": "str",
    "&str": "str",
    "()": "None",
}


def _rust_type_to_python(rust_type: str) -> str:
    """Convert a Rust type string to its Python equivalent."""
    rust_type = rust_type.strip()
    # Unwrap PyResult<T> → T
    m = re.fullmatch(r"PyResult\s*<\s*(.+?)\s*>", rust_type)
    if m:
        return _rust_type_to_python(m.group(1))
    # Strip lifetime annotations like &'_ or &'a
    rust_type = re.sub(r"&'\w+\s+", "&", rust_type)
    return _RUST_TO_PYTHON.get(rust_type, "object")


def _parse_rust_signatures(
    rust_src: str,
) -> dict[str, tuple[list[tuple[str, str]], str, int]]:
    """Return {fn_name: ([("arg", "PyType"), ...], "ReturnType", line_number)} for
    every function preceded by ``#[pyfunction]`` in the Rust source.

    ``line_number`` is the 1-indexed line of the ``pub fn`` keyword so the VS Code
    extension can jump directly to the function definition.
    """
    results: dict[str, tuple[list[tuple[str, str]], str, int]] = {}

    pattern = re.compile(
        r"#\[pyfunction\]"
        r"(?:\s*#\[[^\]]*\])*"          # zero or more other attributes
        r"\s+(pub\s+fn\s+(\w+))"        # group 1: "pub fn name", group 2: name
        r"\s*\(([^)]*)\)"               # group 3: argument list
        r"\s*->\s*([\w<>,\s&']+?)"      # group 4: return type
        r"\s*\{",                        # opening brace
        re.DOTALL,
    )
    for m in pattern.finditer(rust_src):
        fn_name = m.group(2)
        args_str = m.group(3)
        ret_rust = m.group(4).strip()

        # Line number of "pub fn" (1-indexed).
        pub_fn_abs = m.start(1)
        line_num = rust_src[:pub_fn_abs].count("\n") + 1

        args: list[tuple[str, str]] = []
        for arg in args_str.split(","):
            arg = arg.strip()
            if not arg or arg.startswith("_py"):  # skip Python<'_> receiver
                continue
            if ":" in arg:
                arg_name, rust_type = arg.split(":", 1)
                args.append((arg_name.strip(), _rust_type_to_python(rust_type)))
        results[fn_name] = (args, _rust_type_to_python(ret_rust), line_num)

    return results


def main() -> None:
    python_src = REPO_ROOT / "python"
    if str(python_src) not in sys.path:
        sys.path.insert(0, str(python_src))

    try:
        mod = importlib.import_module("mixedlib._rust")
    except ModuleNotFoundError:
        sys.exit(
            "ERROR: mixedlib._rust not found.\n"
            "Run `maturin develop` first, then re-run this script."
        )

    rust_sigs = _parse_rust_signatures(RUST_SOURCE.read_text())

    public_names = sorted(
        name for name in dir(mod)
        if not name.startswith("_") and callable(getattr(mod, name))
    )

    lines = [
        "# AUTO-GENERATED by scripts/gen_stubs.py — do not edit manually.",
        "# Re-run after `maturin develop` whenever Rust functions are added or changed.",
        f"# Rust source: rust/src/lib.rs",
        "",
    ]

    # --- _rust_locations.json (used by the mixedlib-rust-goto VS Code extension) ---
    rust_file_rel = RUST_SOURCE.relative_to(REPO_ROOT).as_posix()
    locations: dict[str, dict] = {}
    for name in public_names:
        if name in rust_sigs:
            _, _, line_num = rust_sigs[name]
            locations[name] = {"file": rust_file_rel, "line": line_num}
    LOCATIONS_PATH.parent.mkdir(exist_ok=True)
    LOCATIONS_PATH.write_text(json.dumps(locations, indent=2) + "\n")
    print(f"Written location map → {LOCATIONS_PATH.relative_to(REPO_ROOT)}")

    # --- _rust.pyi stub ---
    for name in public_names:
        obj = getattr(mod, name)
        if name in rust_sigs:
            args, ret, _ = rust_sigs[name]
            arg_str = ", ".join(f"{n}: {t}" for n, t in args)
            sig = f"({arg_str}) -> {ret}"
        else:
            # Fall back to inspect for functions not found in the Rust source.
            try:
                sig = str(inspect.signature(obj))
            except (ValueError, TypeError):
                sig = "(*args, **kwargs)"

        doc = inspect.getdoc(obj)
        first_doc_line = doc.splitlines()[0] if doc else ""
        if first_doc_line:
            lines.append(f"def {name}{sig}:")
            lines.append(f'    """Rust source: rust/src/lib.rs → pub fn {name}. {first_doc_line}"""')
            lines.append(f"    ...")
        else:
            lines.append(f"def {name}{sig}: ...")

    lines.append("")
    STUB_PATH.write_text("\n".join(lines))

    rel = STUB_PATH.relative_to(REPO_ROOT)
    print(f"Written {len(public_names)} stub(s) → {rel}")
    for name in public_names:
        if name in rust_sigs:
            args, ret, line_num = rust_sigs[name]
            arg_str = ", ".join(f"{n}: {t}" for n, t in args)
            print(f"  def {name}({arg_str}) -> {ret}  # lib.rs:{line_num}")
        else:
            print(f"  def {name}(...)")


if __name__ == "__main__":
    main()
